image: alpine

before_script:
- apk update
- apk add doxygen
- apk add ttf-freefont graphviz
- apk --no-cache add py2-pip python-dev
- pip install sphinx
- apk --no-cache add make

test:
  script:
  - doxygen docs/Doxyfile
  except:
  - master
  
pages:
  script:
  - cd docs
  - mkdir _build
  - mkdit _build/html
  - mkdir _build/html/doxy
  - mkdir _build/latex
  - mkdir _build/latex/doxy
  - doxygen Doxyfile
  - make html
  - cd ..
  - mv docs/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
